### ISSUE TITLE
Check that input files exist

### ISSUE THREAD

**Issue by peterk87** [phac-nml/staramr#11]
When trying to run `staramr` with non-existent input:

```
$ staramr search nofile
```

```
2018-05-07 14:00:39,855 INFO: Scheduling blast for nofile
Traceback (most recent call last):
  File "../staramr/venv/bin/staramr", line 11, in <module>
    load_entry_point('staramr', 'console_scripts', 'staramr')()
  File "../staramr/staramr/main.py", line 70, in main
    args.run_command(args)
  File "../staramr/staramr/subcommand/Search.py", line 170, in run
    args.plength_threshold_pointfinder, args.report_all_blast)
  File "../staramr/staramr/detection/AMRDetection.py", line 63, in run_amr_detection
    resfinder_blast_map = self._amr_detection_handler.get_resfinder_outputs()
  File "../staramr/staramr/blast/BlastHandler.py", line 119, in get_resfinder_outputs
    future_blast.result()
  File "../miniconda3/lib/python3.6/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "../miniconda3/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "../miniconda3/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../staramr/staramr/blast/BlastHandler.py", line 139, in _launch_blast
    stdout, stderr = blastn_command()
  File "../staramr/venv/lib/python3.6/site-packages/Bio/Application/__init__.py", line 523, in __call__
    stdout_str, stderr_str)
Bio.Application.ApplicationError: Non-zero return code 1 from 'blastn -out /tmp/tmpb6o46_2w/nofile.blast.xml -outfmt 5 -query nofile -db ../staramr/staramr/databases/data/dist/resfinder/aminoglycoside.fsa -evalue 0.001', message 'Command line argument error: Argument "query". File is not accessible:  `nofile\''
```

**Comment by apetkau** [comment]
Fixed in https://github.com/phac-nml/staramr/pull/1
