### ISSUE TITLE
Run error in Galaxy 19.05

### ISSUE THREAD

**Issue by PHemarajata** [phac-nml/staramr#123]
Hi, I ran into an error trying to run staramr 0.7.1 in Galaxy. I think this happened after I updated the tool. There is no unresolved dependencies. Please see below. I'd really appreciate any suggestion on what I should do. Thank you so much and stay safe!

2020-07-25 13:30:20 INFO: No --pointfinder-organism specified. Will not search the PointFinder databases
2020-07-25 13:30:20 INFO: No --plasmidfinder-database-type specified. Will search the entire PlasmidFinder database
2020-07-25 13:30:20 INFO: --output-dir not set. Files will be output to the respective --output-[type] setting
2020-07-25 13:30:20 INFO: Will exclude ResFinder/PointFinder genes listed in [/home/phemarajata/galaxy/database/dependencies/_conda/envs/__staramr@0.7.1/lib/python3.7/site-packages/staramr/databases/exclude/data/genes_to_exclude.tsv]. Use --no-exclude-genes to disable
2020-07-25 13:30:20 INFO: Making BLAST databases for input files
2020-07-25 13:30:20 ERROR: list index out of range
Traceback (most recent call last):
  File "/home/phemarajata/galaxy/database/dependencies/_conda/envs/__staramr@0.7.1/lib/python3.7/site-packages/staramr/blast/JobHandler.py", line 286, in _make_blast_db
    subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
  File "/home/phemarajata/galaxy/database/dependencies/_conda/envs/__staramr@0.7.1/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['makeblastdb', '-in', '/home/phemarajata/galaxy/database/tmp/tmpxgo6kvxs/input-genomes/plasmid_AA337.fasta.fasta', '-dbtype', 'nucl', '-parse_seqids']' returned non-zero exit status 1.

**Comment by PHemarajata** [comment]
I'm so sorry. It was my FASTAs that caused it. Should have figured that out earlier.
