### ISSUE TITLE
toList error type

### ISSUE THREAD

**Issue by safinaARK** [phac-nml/staramr#136]
Please help me with the follwoing error:

```
> `2021-10-26 17:31:55 INFO: No --plasmidfinder-database-type specified. Will search the entire PlasmidFinder database
> 2021-10-26 17:31:55 INFO: --output-dir set. All files will be output to [asia_flex_out1]
> 2021-10-26 17:31:55 INFO: Will exclude ResFinder/PointFinder genes listed in [/home/sar/staramr/staramr/databases/exclude/data/genes_to_exclude.tsv]. Use --no-exclude-genes to disable
> 2021-10-26 17:31:57 INFO: Making BLAST databases for input files
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for ERR200399.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for ERR200400.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for ERR200401.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for ERR200402.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for ERR200403.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for ERR200404.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for ERR200405.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for ERR200406.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for ERR200407.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for ERR200408.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for ERR200409.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for ERR200410.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for ERR200411.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for ERR200412.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for ERR217018.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for ERR477384.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11290979.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11290981.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11290982.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11290983.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11290985.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11290986.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11290987.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11290989.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11290990.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11290991.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11290993.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11290994.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291002.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291004.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291005.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291008.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291009.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291010.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291011.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291013.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291014.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291016.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291017.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291019.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291020.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291021.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291022.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291032.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291036.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291038.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291039.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291040.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291041.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291042.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291043.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291044.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291045.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291046.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291048.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291049.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291051.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291052.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291053.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR11291055.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR13767173.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR13767260.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR13767261.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR13767262.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR13767263.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR5437900.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR7893485.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR8836950.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR8836963.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR9639869.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR9639883.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR9639886.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR9639889.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR9673777.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR9673778.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR9673779.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR9673782.fa
> 2021-10-26 17:31:59 INFO: Scheduling blasts and MLST for SRR9673784.fa
> 2021-10-26 17:32:46 ERROR: 'NoneType' object has no attribute 'tolist'
> Traceback (most recent call last):
>   File "/home/sar/staramr/bin/staramr", line 68, in <module>
>     args.run_command(args)
>   File "/home/sar/staramr/staramr/subcommand/Search.py", line 447, in run
>     results = self._generate_results(database_repos=database_repos,
>   File "/home/sar/staramr/staramr/subcommand/Search.py", line 283, in _generate_results
>     amr_detection.run_amr_detection(files,pid_threshold, plength_threshold_resfinder,
>   File "/home/sar/staramr/staramr/detection/AMRDetection.py", line 197, in run_amr_detection
>     self._summary_dataframe = self._create_amr_summary(files, self._resfinder_dataframe,self._quality_module_dataframe,
>   File "/home/sar/staramr/staramr/detection/AMRDetectionResistance.py", line 70, in _create_amr_summary
>     return amr_detection_summary.create_summary(self._include_negative_results)
>   File "/home/sar/staramr/staramr/results/AMRDetectionSummary.py", line 134, in create_summary
>     resistance_frame = self._compile_results(resistance_frame)
>   File "/home/sar/staramr/staramr/results/AMRDetectionSummaryResistance.py", line 40, in _compile_results
>     df_summary = df_summary \
>   File "/home/sar/staramr/.venv/lib/python3.8/site-packages/pandas/core/groupby/generic.py", line 1010, in aggregate
>     result = gba.agg()
>   File "/home/sar/staramr/.venv/lib/python3.8/site-packages/pandas/core/apply.py", line 164, in agg
>     return self.agg_list_like()
>   File "/home/sar/staramr/.venv/lib/python3.8/site-packages/pandas/core/apply.py", line 355, in agg_list_like
>     new_res = colg.aggregate(arg)
>   File "/home/sar/staramr/.venv/lib/python3.8/site-packages/pandas/core/groupby/generic.py", line 249, in aggregate
>     ret = self._aggregate_multiple_funcs(func)
>   File "/home/sar/staramr/.venv/lib/python3.8/site-packages/pandas/core/groupby/generic.py", line 303, in _aggregate_multiple_funcs
>     results[key] = self.aggregate(func)
>   File "/home/sar/staramr/.venv/lib/python3.8/site-packages/pandas/core/groupby/generic.py", line 265, in aggregate
>     return self._python_agg_general(func, *args, **kwargs)
>   File "/home/sar/staramr/.venv/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1332, in _python_agg_general
>     result = self.grouper.agg_series(obj, f)
>   File "/home/sar/staramr/.venv/lib/python3.8/site-packages/pandas/core/groupby/ops.py", line 1049, in agg_series
>     result = self._aggregate_series_fast(obj, func)
>   File "/home/sar/staramr/.venv/lib/python3.8/site-packages/pandas/core/groupby/ops.py", line 1074, in _aggregate_series_fast
>     result, _ = sgrouper.get_result()
>   File "pandas/_libs/reduction.pyx", line 281, in pandas._libs.reduction.SeriesGrouper.get_result
>   File "pandas/_libs/reduction.pyx", line 88, in pandas._libs.reduction._BaseGrouper._apply_to_group
>   File "/home/sar/staramr/.venv/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1318, in <lambda>
>     f = lambda x: func(x, *args, **kwargs)
>   File "/home/sar/staramr/staramr/results/AMRDetectionSummaryResistance.py", line 25, in _aggregate_gene_phenotype
>     flattened_phenotype_list = [y.strip() for x in dataframe.get('Predicted Phenotype').tolist() for y in
> AttributeError: 'NoneType' object has no attribute 'tolist'`
> 
```

My command:
staramr search -o asia_flex_out1 --pointfinder-organism salmonella /home/sar/rgi/asia_flexneri/*fa

Thanks

**Comment by apetkau** [comment]
This has been fixed in #146
