### ISSUE TITLE
ModuleNotFoundError: No module named 'staramr'

### ISSUE THREAD

**Issue by neelam19051** [phac-nml/staramr#142]
Hi, I am trying to install 'staramr' and i am getting this error-
Does anyone know how to solve it? 

Traceback (most recent call last):
  File "/home/bvs/neelam/staramr/bin/staramr", line 44, in <module>
    from staramr import __version__
ModuleNotFoundError: No module named 'staramr'

Thank you!

**Comment by apetkau** [comment]
Hello @neelam19051, how did you install `staramr`? Was it using conda? Pip? Did you clone from GitHub? Which version of Python are you using (`python --version`)?

**Comment by apetkau** [comment]
If possible you will likely want to install `staramr` using the **Bioconda** instructions (https://github.com/phac-nml/staramr#bioconda). Conda/bioconda will install all the necessary non-Python dependencies (like the software [mlst](https://github.com/tseemann/mlst) which is missing and causing the error above).

You can install outside of conda/bioconda too, but then you have to install the following dependencies in addition to `pip install staramr`: https://github.com/phac-nml/staramr#dependencies

**Comment by neelam19051** [comment]
Hi, again i encountered some error, even i installed it with the help of bioconda staramr and the script was same -

**ERROR ##'NoneType' object has no attribute 'tolist'##**

Traceback (most recent call last):
  File "/home/bvs/anaconda3/envs/myenv/bin/staramr", line 68, in <module>
    args.run_command(args)
  File "/home/bvs/anaconda3/envs/myenv/lib/python3.7/site-packages/staramr/subcommand/Search.py", line 468, in run
    unacceptable_num_contigs= args.unacceptable_num_contigs)
  File "/home/bvs/anaconda3/envs/myenv/lib/python3.7/site-packages/staramr/subcommand/Search.py", line 286, in _generate_results
    report_all_blast, ignore_invalid_files, mlst_scheme)
  File "/home/bvs/anaconda3/envs/myenv/lib/python3.7/site-packages/staramr/detection/AMRDetection.py", line 198, in run_amr_detection
    self._pointfinder_dataframe, self._plasmidfinder_dataframe, self._mlst_dataframe)
  File "/home/bvs/anaconda3/envs/myenv/lib/python3.7/site-packages/staramr/detection/AMRDetectionResistance.py", line 70, in _create_amr_summary
    return amr_detection_summary.create_summary(self._include_negative_results)
  File "/home/bvs/anaconda3/envs/myenv/lib/python3.7/site-packages/staramr/results/AMRDetectionSummary.py", line 134, in create_summary
    resistance_frame = self._compile_results(resistance_frame)
  File "/home/bvs/anaconda3/envs/myenv/lib/python3.7/site-packages/staramr/results/AMRDetectionSummaryResistance.py", line 43, in _compile_results
    .aggregate(self._aggregate_gene_phenotype)
  File "/home/bvs/anaconda3/envs/myenv/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 1010, in aggregate
    result = gba.agg()
  File "/home/bvs/anaconda3/envs/myenv/lib/python3.7/site-packages/pandas/core/apply.py", line 164, in agg
    return self.agg_list_like()
  File "/home/bvs/anaconda3/envs/myenv/lib/python3.7/site-packages/pandas/core/apply.py", line 355, in agg_list_like
    new_res = colg.aggregate(arg)
  File "/home/bvs/anaconda3/envs/myenv/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 249, in aggregate
    ret = self._aggregate_multiple_funcs(func)
  File "/home/bvs/anaconda3/envs/myenv/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 303, in _aggregate_multiple_funcs
    results[key] = self.aggregate(func)
  File "/home/bvs/anaconda3/envs/myenv/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 265, in aggregate
    return self._python_agg_general(func, *args, **kwargs)
  File "/home/bvs/anaconda3/envs/myenv/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 1332, in _python_agg_general
    result = self.grouper.agg_series(obj, f)
  File "/home/bvs/anaconda3/envs/myenv/lib/python3.7/site-packages/pandas/core/groupby/ops.py", line 1060, in agg_series
    result = self._aggregate_series_fast(obj, func)
  File "/home/bvs/anaconda3/envs/myenv/lib/python3.7/site-packages/pandas/core/groupby/ops.py", line 1085, in _aggregate_series_fast
    result, _ = sgrouper.get_result()
  File "pandas/_libs/reduction.pyx", line 281, in pandas._libs.reduction.SeriesGrouper.get_result
  File "pandas/_libs/reduction.pyx", line 88, in pandas._libs.reduction._BaseGrouper._apply_to_group
  File "/home/bvs/anaconda3/envs/myenv/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 1318, in <lambda>
    f = lambda x: func(x, *args, **kwargs)
  File "/home/bvs/anaconda3/envs/myenv/lib/python3.7/site-packages/staramr/results/AMRDetectionSummaryResistance.py", line 25, in _aggregate_gene_phenotype
    flattened_phenotype_list = [y.strip() for x in dataframe.get('Predicted Phenotype').tolist() for y in
AttributeError: 'NoneType' object has no attribute 'tolist'


Thank you

**Comment by apetkau** [comment]
Thanks. This looks an awful lot like this issue https://github.com/phac-nml/staramr/issues/136. I believe the solution is to downgrade the `pandas` package:

```
# Or if this does'nt work you can try 'pip install' instead
conda install pandas==1.1.5
```

**Comment by apetkau** [comment]
Fixed in #146
