### ISSUE TITLE
ERROR: ('Error, plasmidfinder database type [{}] is either incorrect or plasmidfinder database not installed properly', 'enterobacteriaceae')

### ISSUE THREAD

**Issue by qianxin-kxy** [phac-nml/staramr#177]
**Hello, very meaningful software!
I would like to determine the plasmid status in the genome of hundreds of Acinetobacter baumannii strains under the infile folder. The code is as follows, and the corresponding error reports are also as follows. Is there a good solution? Or is it said that the software cannot analyze the plasmid situation of Acinetobacter baumannii?**

(staramr) [kxy@zju infile]$ staramr search --plasmidfinder-database-type enterobacteriaceae -o out *.fasta      
                    
2023-06-02 21:44:39,948 WARNING: Using non-default ResFinder/PointFinder. This may lead to differences in the detected AMR genes depending on how the database files are structured.                                                                                                      
2023-06-02 21:44:39,948 INFO: No --pointfinder-organism specified. Will not search the PointFinder databases                                 
2023-06-02 21:44:39,948 ERROR: ('Error, plasmidfinder database type [{}] is either incorrect or plasmidfinder database not installed properly', 'enterobacteriaceae')
Traceback (most recent call last):
  File "/data/users/kxy/miniconda3/envs/staramr/bin/staramr", line 68, in <module>
    args.run_command(args)
  File "/data/users/kxy/miniconda3/envs/staramr/lib/python3.7/site-packages/staramr/subcommand/Search.py", line 337, in run
    'database_type': args.plasmidfinder_database_type})
  File "/data/users/kxy/miniconda3/envs/staramr/lib/python3.7/site-packages/staramr/databases/BlastDatabaseRepositories.py", line 161, in build_blast_database
    return PlasmidfinderBlastDatabase(self.get_repo_dir(database_name), options['database_type'])
  File "/data/users/kxy/miniconda3/envs/staramr/lib/python3.7/site-packages/staramr/blast/plasmidfinder/PlasmidfinderBlastDatabase.py", line 34, in __init__
    database_type)
Exception: ('Error, plasmidfinder database type [{}] is either incorrect or plasmidfinder database not installed properly', 'enterobacteriaceae')

**Comment by apetkau** [comment]
As mentioned in https://github.com/phac-nml/staramr/issues/169, `enterobacteriaceae` is out of date and it should be `enterobacteriales`. Though why it didn't automatically switch I'm not sure.

Note if you leave `--plasmidfinder-database-type` as the default it will search using all the fasta files from the PlasmidFinder database.

**Comment by qianxin-kxy** [comment]
> As mentioned in #169, `enterobacteriaceae` is out of date and it should be `enterobacteriales`. Though why it didn't automatically switch I'm not sure.
> 
> Note if you leave `--plasmidfinder-database-type` as the default it will search using all the fasta files from the PlasmidFinder database.

Thank you for your reply. After I update Staramr to the latest version of 0.9.1 and replace the code with $ staramr search --plasmidfinder-database-type enterobacteriales -o out *.fasta, it can run normally
