### ISSUE TITLE
staramr in Galaxy error

### ISSUE THREAD

**Issue by PHemarajata** [phac-nml/staramr#18]
Hi,
I installed staramr in Galaxy on a native Ubuntu, and got an error trying after using a Shovill-assembled configs (in a multi-fasta file). I was wondering what I did wrong and would appreciate any suggestion. Thank you!

`Fatal error: Exit code 1 ()
2018-06-10 14:51:10,922 INFO: No --pointfinder-organism specified. Will not search the PointFinder databases
2018-06-10 14:51:10,922 INFO: --output-dir not set. Files will be output to the respective --output-[type] setting
2018-06-10 14:51:10,931 INFO: Making BLAST databases for input files
2018-06-10 14:51:10,939 ERROR: Command '['makeblastdb', '-in', '/home/phemarajata/galaxy/database/tmp/tmpuuzos1zh/input-genomes/Shovill on data 11 and data 10: Contigs.fasta', '-dbtype', 'nucl', '-parse_seqids']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/phemarajata/galaxy/database/dependencies/_conda/envs/__staramr@0.2.0/bin/staramr", line 68, in 
    args.run_command(args)
  File "/home/phemarajata/galaxy/database/dependencies/_conda/envs/__staramr@0.2.0/lib/python3.6/site-packages/staramr/subcommand/Search.py", line 356, in run
    files=args.files)
  File "/home/phemarajata/galaxy/database/dependencies/_conda/envs/__staramr@0.2.0/lib/python3.6/site-packages/staramr/subcommand/Search.py", line 216, in _generate_results
    plength_threshold_pointfinder, report_all_blast)
  File "/home/phemarajata/galaxy/database/dependencies/_conda/envs/__staramr@0.2.0/lib/python3.6/site-packages/staramr/detection/AMRDetection.py", line 61, in run_amr_detection
    self._amr_detection_handler.run_blasts(files)
  File "/home/phemarajata/galaxy/database/dependencies/_conda/envs/__staramr@0.2.0/lib/python3.6/site-packages/staramr/blast/BlastHandler.py", line 96, in run_blasts
    db_files = self._make_db_from_input_files(self._input_genomes_tmp_dir, files)
  File "/home/phemarajata/galaxy/database/dependencies/_conda/envs/__staramr@0.2.0/lib/python3.6/site-packages/staramr/blast/BlastHandler.py", line 120, in _make_db_from_input_files
    future_blastdb.result()
  File "/home/phemarajata/galaxy/database/dependencies/_conda/envs/__staramr@0.2.0/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/phemarajata/galaxy/database/dependencies/_conda/envs/__staramr@0.2.0/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/phemarajata/galaxy/database/dependencies/_conda/envs/__staramr@0.2.0/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/phemarajata/galaxy/database/dependencies/_conda/envs/__staramr@0.2.0/lib/python3.6/site-packages/staramr/blast/BlastHandler.py", line 196, in _make_blast_db
    subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE).check_returncode()
  File "/home/phemarajata/galaxy/database/dependencies/_conda/envs/__staramr@0.2.0/lib/python3.6/subprocess.py", line 369, in check_returncode
    self.stderr)
subprocess.CalledProcessError: Command '['makeblastdb', '-in', '/home/phemarajata/galaxy/database/tmp/tmpuuzos1zh/input-genomes/Shovill on data 11 and data 10: Contigs.fasta', '-dbtype', 'nucl', '-parse_seqids']' returned non-zero exit status 1.`

**Comment by apetkau** [comment]
Woops, looks like I forgot to test the case where there's spaces in the input dataset filename in Galaxy.  I've made an issue for this https://github.com/phac-nml/staramr/issues/19.

In the meantime, could you rename the dataset **Shovill on data 11 and data 10: Contigs.fasta** to remove the spaces in the name?

**Comment by PHemarajata** [comment]
It works! Thank you so much. I'm developing a Galaxy instance for my microbiologists and I love this all-in-one tool.

**Comment by apetkau** [comment]
No problem. I'm glad it's useful. If you have any other questions let me know.

**Comment by apetkau** [comment]
This should now be permanently fixed @PHemarajata. You will have to update the Galaxy tool to get the fix.
