### ISSUE TITLE
an unexpected keyword argument "inplace" and can't out the "results.xlxs"

### ISSUE THREAD

**Issue by Yovelaaa** [phac-nml/staramr#184]
2023-07-24 18:54:21 INFO: Predicting AMR resistance phenotypes is enabled. The predictions are for microbiological resistance and *not* clinical resistance. These results are continually being improved and we welcome any feedback.
2023-07-24 18:54:21 INFO: Writing resfinder to [/public/home/2021180/caoyue/20SCAPR/negative/staramr/resfinder.tsv]
2023-07-24 18:54:21 INFO: --output-dir or --output-pointfinder unset. No pointfinder file will be written
2023-07-24 18:54:21 INFO: Writing plasmidfinder to [/public/home/2021180/caoyue/20SCAPR/negative/staramr/plasmidfinder.tsv]
2023-07-24 18:54:21 INFO: Writing summary to [/public/home/2021180/caoyue/20SCAPR/negative/staramr/summary.tsv]
2023-07-24 18:54:21 INFO: Writing MLST summary to [/public/home/2021180/caoyue/20SCAPR/negative/staramr/mlst.tsv]
2023-07-24 18:54:21 INFO: Writing detailed summary to [/public/home/2021180/caoyue/20SCAPR/negative/staramr/detailed_summary.tsv]
2023-07-24 18:54:21 INFO: Writing settings to [/public/home/2021180/caoyue/20SCAPR/negative/staramr/settings.txt]
2023-07-24 18:54:21 INFO: Writing Excel to [/public/home/2021180/caoyue/20SCAPR/negative/staramr/results.xlsx]
2023-07-24 18:54:21 ERROR: DataFrame.set_axis() got an unexpected keyword argument 'inplace'
Traceback (most recent call last):
  File "/public/home/2021180/miniconda3/envs/staramr/bin/staramr", line 68, in <module>
    args.run_command(args)
  File "/public/home/2021180/miniconda3/envs/staramr/lib/python3.11/site-packages/staramr/subcommand/Search.py", line 544, in run
    settings_dataframe.set_axis(['Value'], axis='columns', inplace=True)
TypeError: DataFrame.set_axis() got an unexpected keyword argument 'inplace'
2023-07-24 18:54:22 INFO: No --pointfinder-organism specified. Will not search the PointFinder databases
2023-07-24 18:54:22 INFO: PlasmidFinder database type [enterobacteriaceae] is out of date, switching to [enterobacteriales]
2023-07-24 18:54:22 ERROR: Output directory [/public/home/2021180/caoyue/20SCAPR/negative/staramr/] already exists

**Comment by apetkau** [comment]
Hello @Yovelaaa, it looks like pandas removed `DataFrame.set_axis` for version 2.0.0. To get staramr to work, you will have to install a version of pandas < 2.0.0. For example:

```bash
conda create --name staramr staramr 'pandas<2'
```

**Comment by Yovelaaa** [comment]
> Hello @Yovelaaa, it looks like pandas removed `DataFrame.set_axis` for version [2.0.0](https://pandas.pydata.org/docs/whatsnew/v2.0.0.html#removal-of-prior-version-deprecations-changes). To get staramr to work, you will have to install a version of pandas < 2.0.0. For example:
> 
> ```shell
> conda create --name staramr staramr 'pandas<2'
> ```
It works! Thank you very much!

**Comment by apetkau** [comment]
Fixed in #193
