### ISSUE TITLE
Output to individual files is raising an exception (development)

### ISSUE THREAD

**Issue by apetkau** [phac-nml/staramr#72]
When running with output to single files `--output-summary summary.tsv` I get the following exception:

```
2019-04-12 11:00:20,475 ERROR: 'Namespace' object has no attribute 'output_detailed_summary'
Traceback (most recent call last):
  File "/home/CSCScience.ca/apetkau/workspace/staramr/bin/staramr", line 68, in <module>
    args.run_command(args)
  File "/home/CSCScience.ca/apetkau/workspace/staramr/staramr/subcommand/Search.py", line 375, in run
    output_detailed_summary = args.output_detailed_summary
AttributeError: 'Namespace' object has no attribute 'output_detailed_summary'
```

I think an argument for `--output-detailed-summary` is missing.

**Comment by apetkau** [comment]
Fixed in #73
